package dotenv

import (
	"fmt"
	"os"
	"strings"

	"github.com/joho/godotenv"
	"github.com/tcaty/spa-env/internal/common/log"
	"github.com/tcaty/spa-env/internal/common/utils"
	"github.com/tcaty/spa-env/pkg/file"
)

// Find dotenv file in workdir by filename and read it
// return map in form of [key]: [placeholder]
func Read(workdir string, filename string) (map[string]string, error) {
	path, err := file.Find(workdir, filename)
	if err != nil {
		return nil, fmt.Errorf("error occured while finding .env file: %v", err)
	}

	content, err := godotenv.Read(path)
	if err != nil {
		return nil, fmt.Errorf("error occured while reading %s file: %v", path, err)
	}

	log.Debug(
		".env file was found successfully",
		"path", path,
	)

	return content, nil
}

// Find dotenv file in workdir by filename and write envMap there
func Write(envMap map[string]string, workdir, filename, placeholderPrefix string, enableComments bool) error {
	path := fmt.Sprintf("%s%s", utils.AddSuffix(workdir, "/"), filename)

	content := generateContent(envMap, placeholderPrefix, enableComments)
	file, err := os.Create(path)
	if err != nil {
		return err
	}

	defer file.Close()

	_, err = file.WriteString(content + "\n")
	if err != nil {
		return err
	}

	if err := file.Sync(); err != nil {
		return err
	}

	log.Debug(
		"successful write to .env file",
		"path", path,
	)

	return nil
}

func generateContent(envMap map[string]string, placeholderPrefix string, enableComments bool) string {
	content := make([]string, 0)

	if enableComments {
		content = append(
			content,
			"# This file was auto-generated by spa-env tool. Don't edit it manually!",
			"# There is a full list of client environment variables below",
			"#",
		)

		for _, v := range envMap {
			content = append(content, fmt.Sprintf("# %s", strings.TrimPrefix(v, placeholderPrefix)))
		}
	}

	for k, v := range envMap {
		if enableComments {
			content = append(
				content,
				fmt.Sprintf("\n# env -> %s", strings.TrimPrefix(v, placeholderPrefix)),
				fmt.Sprintf("# src -> process.env.%s", k),
			)
		}
		content = append(content, fmt.Sprintf("%s=%s", k, v))
	}

	return strings.Join(content, "\n")
}
