version: "3"
  
services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile
    command: --verbose
    restart: unless-stopped
    environment:
      API_URL: "https://api.com/"
      SECRET_TOKEN: "54321"
    ports:
      - "3000:3000"
