version: "3"
  
services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile
    command: --log-level DEBUG
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
