version: "3"
  
services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile
    command: --verbose
    restart: unless-stopped
    environment:
      # server variables
      POSTGRES_CONN_STRING: "postgres://username:password@prod.server:5432/database"
      # client variables
      API_URL: "https://api.com/"
      SECRET_TOKEN: "54321"
    ports:
      - "3000:3000"
