name: Lint & Test
    
on:
  pull_request:
    types: 
      - opened 
      - synchronize
      - reopened
      
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.5"
      - name: Install dependencies
        run: go get .
      - name: Run golangci linter
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.58.0
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test
          